export const facets = [
  {
    id: null,
    label: 'Price',
    type: 'price',
    options: [
      {
        id: 'pr1',
        label: 'Under $24.99',
        value: 'under',
      },
      {
        id: 'pr2',
        label: '$25.00 - $49.99',
        value: '25-49',
      },
      {
        id: 'pr3',
        label: '$50.00 - $99.99',
        value: '50-99',
      },
      {
        id: 'pr4',
        label: '$100.00 - $199.99',
        value: '100-199',
      },
      {
        id: 'pr5',
        label: '$200.00 and above',
        value: 'above',
      },
    ],
  },
  {
    id: '5',
    label: 'Size',
    attributeName: 'Size',
    type: 'select',
    count: 0,
    options: [
      {
        id: '5-9',
        value: 9,
        label: '5',
        metadata: '5-9',
        htmlColor: null,
      },
      {
        id: '5-10',
        value: 10,
        label: '6',
        metadata: '5-10',
        htmlColor: null,
      },
      {
        id: '5-11',
        value: 11,
        label: '7',
        metadata: '5-11',
        htmlColor: null,
      },
      {
        id: '5-12',
        value: 12,
        label: '8',
        metadata: '5-12',
        htmlColor: null,
      },
      {
        id: '5-13',
        value: 13,
        label: '9',
        metadata: '5-13',
        htmlColor: null,
      },
      {
        id: '5-14',
        value: 14,
        label: '10',
        metadata: '5-14',
        htmlColor: null,
      },
      {
        id: '5-15',
        value: 15,
        label: '11',
        metadata: '5-15',
        htmlColor: null,
      },
      {
        id: '5-16',
        value: 16,
        label: '12',
        metadata: '5-16',
        htmlColor: null,
      },
      {
        id: '5-17',
        value: 17,
        label: '13',
        metadata: '5-17',
        htmlColor: null,
      },
      {
        id: '5-18',
        value: 18,
        label: '34',
        metadata: '5-18',
        htmlColor: null,
      },
      {
        id: '5-19',
        value: 19,
        label: '35',
        metadata: '5-19',
        htmlColor: null,
      },
      {
        id: '5-20',
        value: 20,
        label: '36',
        metadata: '5-20',
        htmlColor: null,
      },
      {
        id: '5-21',
        value: 21,
        label: '37',
        metadata: '5-21',
        htmlColor: null,
      },
      {
        id: '5-22',
        value: 22,
        label: '38',
        metadata: '5-22',
        htmlColor: null,
      },
      {
        id: '5-24',
        value: 24,
        label: '40',
        metadata: '5-24',
        htmlColor: null,
      },
      {
        id: '5-25',
        value: 25,
        label: '41',
        metadata: '5-25',
        htmlColor: null,
      },
      {
        id: '5-26',
        value: 26,
        label: '42',
        metadata: '5-26',
        htmlColor: null,
      },
      {
        id: '5-27',
        value: 27,
        label: '43',
        metadata: '5-27',
        htmlColor: null,
      },
      {
        id: '5-28',
        value: 28,
        label: '44',
        metadata: '5-28',
        htmlColor: null,
      },
      {
        id: '5-29',
        value: 29,
        label: '45',
        metadata: '5-29',
        htmlColor: null,
      },
      {
        id: '5-30',
        value: 30,
        label: '46',
        metadata: '5-30',
        htmlColor: null,
      },
      {
        id: '5-31',
        value: 31,
        label: '47',
        metadata: '5-31',
        htmlColor: null,
      },
      {
        id: '5-32',
        value: 32,
        label: '48',
        metadata: '5-32',
        htmlColor: null,
      },
      {
        id: '5-33',
        value: 33,
        label: '49',
        metadata: '5-33',
        htmlColor: null,
      },
      {
        id: '5-34',
        value: 34,
        label: '50',
        metadata: '5-34',
        htmlColor: null,
      },
      {
        id: '5-35',
        value: 35,
        label: '51',
        metadata: '5-35',
        htmlColor: null,
      },
      {
        id: '5-36',
        value: 36,
        label: '52',
        metadata: '5-36',
        htmlColor: null,
      },
    ],
  },
  {
    id: '6',
    label: 'Material',
    attributeName: 'Material',
    type: 'radio',
    count: 0,
    options: [
      {
        id: '6-37',
        value: 37,
        label: 'Cotton',
        metadata: '6-37',
        htmlColor: null,
      },
      {
        id: '6-38',
        value: 38,
        label: 'Leather',
        metadata: '6-38',
        htmlColor: null,
      },
    ],
  },
  {
    id: '7',
    label: 'Color',
    attributeName: 'Color',
    type: 'color',
    count: 0,
    options: [
      {
        id: '7-41',
        value: 41,
        label: 'Grey',
        metadata: '7-41',
        htmlColor: '#bfbfbf',
      },
      {
        id: '7-45',
        value: 45,
        label: 'Blue',
        metadata: '7-45',
        htmlColor: '#0c7af7',
      },
      {
        id: '7-46',
        value: 46,
        label: 'Green',
        metadata: '7-46',
        htmlColor: '#14c00b',
      },
      {
        id: '7-47',
        value: 47,
        label: 'Brown',
        metadata: '7-47',
        htmlColor: '#964B00',
      },
      {
        id: '7-43',
        value: 43,
        label: 'Red',
        metadata: '7-43',
        htmlColor: '#f40000',
      },
    ],
  },
];
